name: "Archetect Render Action"
description: "GitHub Action to render Archetypes using Archetect https://github.com/archetect/archetect"
branding:
  icon: "activity"
  color: "blue"
inputs:
  version:
    description: The Archetect version (https://github.com/archetect/archetect/releases)
    required: false
    default: "v2.0.0"
  source:
    description: The source directory or Git repo containing an Archetype
    required: true
  destination:
    description: The destination of the rendered output
    required: false
    default: "."
  answers:
    description: Answers in JSON Object (key/value) Format.  Answers may also be applied using 'args'
    required: false
    default: "{}"
  args:
    description: Additional command-line arguments for the archetect command (e.g. -a, -A, -s)
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Archetect
      shell: bash
      run: |
        echo "Download Archetect"
        version="${{ inputs.version }}"
        pushd "${{ runner.temp }}"
        curl -LO "https://github.com/archetect/archetect/releases/download/$version/archetect-$version-linux_x64.tar.gz" 2>/dev/null
        tar -xvzf ./archetect-$version-linux_x64.tar.gz
        mv ./archetect-$version-linux_x64/archetect .
        popd
        echo "ARCHETECT=${{ runner.temp }}/archetect" >> $GITHUB_ENV
    - name: Write Answers
      shell: bash
      run: |
        _answers = "${{ inputs.answers }}"
        echo "ANSWERS (ENV): ${_answers}"
        echo "ANSWERS (Pre Write): ${{ inputs.answers }}"
        echo "ANSWERS (fromJson): ${{ fromJson(inputs.answers) }}"
        echo "ANSWERS (toJson): ${{ toJson(inputs.answers) }}"
        echo  
        pushd "${{ runner.temp }}"
        echo "${{ fromJson(inputs.answers) }}" > answers.json
        popd
        echo "ANSWERS=${{ runner.temp }}/answers.json" >> $GITHUB_ENV
    - name: Render Archetype
      shell: bash
      run: |
        echo "Rendering: [Source: ${{ inputs.source }}, Destination: ${{ inputs.destination }}, Arguments: ${{ inputs.args }}]"
        echo "JSON Answers:"
        cat "${{ runner.temp }}/answers.json"
        flags="--headless"
        $ARCHETECT render $flags -A "$ANSWERS" ${{ inputs.source }} ${{ inputs.args }} ${{ inputs.destination }}
